version: '3.1'

services:

  wordpress:
    build: .
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: change_me
      WORDPRESS_DB_PASSWORD: change_me
      WORDPRESS_DB_NAME: change_me
      # test bucket
      S3_ENDPOINT: https://objects.k3s-prod.francoz.net
      S3_BUCKET: wordpress-upload
      S3_REGION: fake-region
      S3_ACCESS_KEY: HC3E4YJ40XWIJERF80C2
      S3_SECRET: J8YE3yRCTo4fA95nDdphqkjyycmY5DZO7XtAfZxe
      S3_USE_PATH_STYLE: true
      S3_PROVISIONNER: ceph
      #MCLOUD_TOOL_ENABLED_STORAGE: true

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: change_me
      MYSQL_USER: change_me
      MYSQL_PASSWORD: change_me
      MYSQL_DATABASE: change_me
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
