apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: 1
  {{- end }}
  selector:
    matchLabels:
      {{- include "mariadb.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mariadb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mariadb.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: {{ include "mariadb.fullname" . }}-data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.fullname" . }}
                  key: MARIADB_ROOT_PASSWORD
                  optional: false
            - name: MARIADB_USER
              value: {{ required "username" .Values.username }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mariadb.fullname" . }}
                  key: MARIADB_PASSWORD
                  optional: false
            - name: MARIADB_DATABASE
              value: {{ required "database" .Values.database }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          startupProbe:
            failureThreshold: 12
            tcpSocket:
              port: mysql
          livenessProbe:
            tcpSocket:
              port: mysql
          readinessProbe:
            tcpSocket:
              port: mysql
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: mariadb-data
              mountPath: /var/lib/mysql
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
