apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
data:
  MARIADB_ROOT_PASSWORD: {{
    include "getOrGeneratePass" 
      ( dict
        "Namespace" .Release.Namespace
        "Kind" "Secret"
        "Name" (include "mariadb.fullname" .)
        "Key" "MARIADB_ROOT_PASSWORD"
        "Default" .Values.rootPassword
      )
    }}
  MARIADB_PASSWORD: {{
    include "getOrGeneratePass"
      ( dict
        "Namespace" .Release.Namespace
        "Kind" "Secret"
        "Name" (include "mariadb.fullname" .)
        "Key" "MARIADB_PASSWORD"
        "Default" .Values.Password
      )
    }}
