apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "wordpress.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wordpress.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wordpress.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      #volumes:
      #  - name: app-caddy
      #    emptyDir: {}
      #  - name: var-www
      #    emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: WORDPRESS_DB_NAME
              value: {{ required "database.name" .Values.database.name }}
            - name: WORDPRESS_DB_USER
              value: {{ required "database.name" .Values.database.user }}
            - name: WORDPRESS_DB_PASSWORD
              value: {{ required "database.name" .Values.database.password }}
            - name: WORDPRESS_DB_HOST
              value: {{ required "database.name" .Values.database.host }}
            - name: WP_REDIS_HOST
              value: {{ required "redis.host" .Values.redis.host }}
            - name: WP_REDIS_PORT
              value: {{ .Values.redis.port | default 6379 | quote }}
            - name: MCLOUD_STORAGE_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ required "bucket.existingSecret" .Values.bucket.existingSecret }}
                  key: AWS_ACCESS_KEY_ID
                  optional: false 
            - name: MCLOUD_STORAGE_S3_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ required "bucket.existingSecret" .Values.bucket.existingSecret }}
                  key: AWS_SECRET_ACCESS_KEY
                  optional: false 
            - name: MCLOUD_STORAGE_PROVIDER
              value: {{ required "bucket.provider" .Values.bucket.provider | quote }}
            - name: MCLOUD_STORAGE_S3_BUCKET
              value: {{ required "bucket.name" .Values.bucket.name | quote }}
            - name: MCLOUD_STORAGE_S3_ENDPOINT
              value: {{ required "bucket.endpoint" .Values.bucket.endpoint | quote }}
            - name: MCLOUD_STORAGE_S3_USE_PATH_STYLE_ENDPOINT
              value: {{ required "bucket.usePathStyle" .Values.bucket.usePathStyle | quote }}
            - name: MCLOUD_TOOL_ENABLED_STORAGE
              value: "true"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /wp/wp-admin/install.php
              port: http
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /wp/wp-admin/install.php
              port: http
              scheme: HTTP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          #volumeMounts:
          #  - name: app-caddy
          #    mountPath: /app/caddy
          #  - name: var-www
          #    mountPath: /var/www
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "wordpress.fullname" . }}
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
