{{- if ((.Values.prometheus).blackboxProberUrl) }}
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "wordpress.fullname" . }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  jobName: http-get
  interval: 60s
  module: http_2xx
  prober:
    url: {{ .Values.prometheus.blackboxProberUrl }}:9115
    scheme: http
    path: /probe
  targets:
    staticConfig:
      static:
      {{- range .Values.ingress.hosts }}
      - https://{{ .host }}/
      {{- end }}
{{- end }}
