{{- if eq .Values.provisionner.type "ceph" }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "bucket.fullname" . }}
spec:
  bucketName: {{ .Values.name }}
  generateBucketName: {{ .Values.name }}
  storageClassName: {{ .Values.provisionner.storageClassName }}
  additionalConfig:
    {{- .Values.provisionner.additionalConfig | toYaml | nindent 4 }}
{{- end }}
