image:
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
  - host: wptest2.k3s-prod.francoz.net
    paths:
    - path: /
      pathType: Prefix
  tls:
    - hosts:
        - wptest2.k3s-prod.francoz.net

prometheus:
  blackboxProberUrl: blackbox-prometheus-blackbox-exporter.infra-blackbox-exporter

autoscaling:
  enabled: false

resources:
  requests:
    memory: 256M

mariadb:
  enabled: true
  resources:
    requests:
      memory: 256Mi

redis:
  enabled: true
  resources:
    requests:
      memory: 10Mi

bucket:
  provisionner:
    type: ceph
  provider: other-s3
  name: wordpress-upload
  endpoint: https://objects.k3s-prod.francoz.net
  usePathStyle: true
