image:
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
  - host: wptest2.k3s-prod.francoz.net
    paths:
    - path: /
      pathType: Prefix
  tls:
    - hosts:
        - wptest2.k3s-prod.francoz.net

resources:
  requests:
    memory: 256M

mariadb:
  enabled: true

redis:
  enabled: true

bucket:
  provisionner:
    type: ceph
  provider: other-s3
  name: wordpress-upload
  endpoint: https://objects.k3s-prod.francoz.net
  usePathStyle: true
